# frozen_string_literal: true

# Writes the generated Swift files of the Swift port of pxl.h: the built-in
# shaders and font, and the shaders of the tests.
#
#   ruby swift/tools/generate.rb
#
# It copies the shaders that pxl.h and tests/pxl/test_shaders.h embed, so it
# needs no shader compiler. Run "rake pxl:generate" first when the GLSL
# changes. The font comes from tools/pxl/font.txt.

require "fileutils"
require_relative "../../tools/pxl/font"

module PxlSwift
  ROOT = File.expand_path("../..", __dir__)
  SWIFT = File.join(ROOT, "swift")
  HEADER = "// swift-format-ignore-file\n// Generated by swift/tools/generate.rb. Do not edit.\n"

  module_function

  # Returns the byte arrays of a C file: name => bytes.
  def c_arrays(path)
    File.read(path).scan(/static const uint8_t (\w+)\[\] = \{(.*?)\};/m).to_h do |name, body|
      [name, body.scan(/0x\h\h/).map(&:hex).pack("C*")]
    end
  end

  # Returns the Swift name of a C shader array: pxl__sprite_frag_spirv ->
  # spriteFragSPIRV.
  def swift_name(c_name)
    *words, format = c_name.delete_prefix("pxl__").split("_")
    words.first + words.drop(1).map(&:capitalize).join + format.upcase
  end

  def byte_array(name, bytes)
    lines = bytes.bytes.each_slice(12).map { |line| "  #{line.map { |b| format('0x%02x', b) }.join(', ')}," }
    "let #{name}: [UInt8] = [\n#{lines.join("\n")}\n]\n"
  end

  # Returns MSL source as a raw string literal. The literal drops the last
  # line break before its end, so the text keeps its own.
  def text(name, bytes)
    source = bytes.dup.force_encoding(Encoding::UTF_8)
    abort("#{name}: the MSL is not UTF-8") unless source.valid_encoding?
    abort("#{name}: the MSL contains \"\"\"#") if source.include?('"""#')
    "let #{name} = #\"\"\"\n#{source}\n\"\"\"#\n"
  end

  # Returns the Swift constants of the shaders of a C file.
  def shader_constants(arrays)
    arrays.map do |c_name, bytes|
      name = swift_name(c_name)
      c_name.end_with?("_msl") ? text(name, bytes) : byte_array(name, bytes)
    end.join("\n")
  end

  # Returns a ShaderDescriptor for each pxl_shader_desc of a C file.
  def shader_descriptors(path)
    File.read(path).scan(/static const pxl_shader_desc (\w+) = \{(.*?)\};/m).map do |c_name, body|
      prefix = swift_name("#{c_name}_x").delete_suffix("X")
      textures = body[/\.num_textures = (\d+)/, 1]
      uniforms = body[/\.has_uniforms = (\w+)/, 1]
      <<~SWIFT
        let #{prefix} = ShaderDescriptor(
          spirv: ShaderCode(#{prefix}SPIRV),
          dxil: ShaderCode(#{prefix}DXIL),
          msl: ShaderCode(source: #{prefix}MSL),
          textureCount: #{textures},
          hasUniforms: #{uniforms}
        )
      SWIFT
    end.join("\n")
  end

  def font_constants
    glyphs = PxlFont.parse(File.join(ROOT, "tools/pxl/font.txt"))
    rows = []
    advances = []
    PxlFont::COUNT.times do |index|
      code = PxlFont::FIRST + index
      glyph = glyphs.fetch(code.chr)
      bits = Array.new(PxlFont::HEIGHT) { |row| PxlFont.row_bits(glyph[row] || "") }
      rows << format("  %s, // 0x%02x", bits.map { |b| format("0x%02x", b) }.join(", "), code)
      advances << PxlFont.advance(code.chr, glyph)
    end
    advance_lines = advances.each_slice(16).map { |line| "  #{line.join(', ')}," }
    <<~SWIFT
      /// The glyphs of the built-in font from U+0020, #{PxlFont::HEIGHT} rows each. Bit
      /// #{PxlFont::WIDTH - 1} is the left column.
      let fontRows: [UInt8] = [
      #{rows.join("\n")}
      ]

      /// The advance of each glyph of the built-in font in pixels.
      let fontAdvances: [UInt8] = [
      #{advance_lines.join("\n")}
      ]
    SWIFT
  end

  def write(path, body)
    output = File.join(SWIFT, path)
    FileUtils.mkdir_p(File.dirname(output))
    File.write(output, "#{HEADER}\n#{body}")
    puts "wrote swift/#{path}"
  end

  def run
    write("Sources/Pxl/Generated.swift",
          "#{shader_constants(c_arrays(File.join(ROOT, 'pxl.h')))}\n#{font_constants}")
    tests = File.join(ROOT, "tests/pxl/test_shaders.h")
    write("Tests/PxlTests/TestShaders.swift",
          "import Pxl\n\n#{shader_descriptors(tests)}\n#{shader_constants(c_arrays(tests))}")
  end
end

PxlSwift.run if $PROGRAM_NAME == __FILE__
